### PR TITLE
Use harmony theme

### PR DESCRIPTION
**Pull request by friedger**
This PR adds the responsive Harmony theme to github pages. This is to have a start for a design.

**Before**
screenshot 2015-05-19 19 11 30

**After**
screenshot 2015-05-19 18 57 14

There is still an issue with code blocks.

### CODE REVIEW

**Comment by blundell** [comment]
I thought @DigitalPencils was working on designs for all open source webpages. If we add this we have inconsistencies

**Comment by friedger** [comment]
@blundell for reference https://novoda.atlassian.net/projects/DES/issues/DES-74

**Comment by devisnik** [comment]
@friedger I can not access above issue.

**Comment by friedger** [comment]
@devisnik who is your buddy? :-P

**Comment by friedger** [comment]
@digitalpencils is this good enough to be merged?

**Comment by devisnik** [comment]
:+1:

**Comment by DigitalPencils** [comment]
Ok ok ... my githubs were going into spam. I didn't see this.  @friedger can we chat about these things tomorrow?

**Comment by xrigau** [comment]
:100: @friedger

**Pull request merged**
