### PR TITLE
fix java compatibility

### PR DESCRIPTION
**Pull request by devisnik**
Release 0.3.0 require java8. 
This PR fixes that (ensuring java6 compatibility) and prepares for deploying version 0.3.1.

### CODE REVIEW

**Comment by blundell** [comment]
Why do you still want to support J6? :-) don't want to push everyone forwards? J7 at least ...

**Comment by ouchadam** [comment]
if the lib doesn't need java 7 it should force 6 :+1:

**Comment by blundell** [comment]
I'm sure it must use one Collection (diamond operator)

**Comment by devisnik** [comment]
As long as we're not hurt by supporting java6 I wouldn't force users into that.

**Comment by blundell** [comment]
it's up to you, I just think its encouraging people to not think about upgrading :+1:

**Comment by devisnik** [comment]
@blundell It's not encouraging them to upgrade, which is not quite the same. ;)

**Pull request merged**
