### PR TITLE
prepare release of version 0.3.2

### PR DESCRIPTION
**Pull request by devisnik**
- increments version to 0.3.2
- updates readme

### CODE REVIEW

**Comment by danybony** [comment]
:100: LGTM

**Comment by danybony** [comment]
Mmm, changed my mind, not entirely good :tongue: 
can you update the `build.gradle` in the two demo projects with the updated `apply plugin: 'com.novoda.sqlite-analyzer'` ?

**Comment by devisnik** [comment]
Oh, yes, will do. :+1:

**Comment by ouchadam** [comment]
:100: wooo

**Comment by danybony** [comment]
:+1:

**Pull request merged**
