### PR TITLE
Add analyzer module back in settings.gradle

### PR DESCRIPTION
**Pull request by ataulm**
@devisnik @stefanhoth Not sure why it was [removed](https://github.com/novoda/sqlite-analyzer/commit/b96b8191c68793198072484afd3ee511c065a6a7), so would prefer input from these fellows.

- the bintray release plugin is found in here and without this module the CI build will crash (uses bintrayUpload)

### CODE REVIEW

**Comment by devisnik** [comment]
The actual gradle plugin project (in the `analyzer` folder) is now its own gradle project, the root project is just linking it under its `buildSrc` folder to use it for building the demo projects. 

We had some path resolving issues with the latest AS when keeping it in the main project, which was a hack anyway to make this setup work in earlier AS versions. 

You can now work on the demos and on the actual plugin via two separate AS projects. Only the plugin project needs the bintray upload then. CI should be set up accordingly.

**Comment by ataulm** [comment]
So if they're in two separate AS projects - should they be in two separate repos?

Why don't the demo modules reference the `analyzer` module in their dependencies (the same way we might reference `core` from an `android` module)?

@blundell there should be some convention on this, being a NOS project - where all libs typically have a demo project, so they'll all be affected by the same issues?

**Comment by ataulm** [comment]
@devisnik even if the bintrayUpload is run only on the `analyzer` module (I've modified the CI script to do this), the root project still needs to know about the module by including it in `settings.gradle`.

Do you mean something else by setting up the CI accordingly so it can be done without this?

**Comment by devisnik** [comment]
@ataulm I mean `analyzer` is a separate gradle project. It does not depend on the root project. We only link it into that one via the `buildSrc` folder so we can use it in the demo projects without an extra deployment step. 
Can't we run the `bintrayUpload` task inside the `anaylzer` folder?

May be the set-up is not ideal, we could make `analyzer` the default (root) project and put the demos root into a sub-folder if that is easier.

**Comment by devisnik** [comment]
@ataulm `analyzer` is not a regular dependency of the demo projects, it is a buildscript dependency.

**Comment by orangeman** [comment]
Such many directories and folders seems unecessary confusing.
The library *sqlite-analyzer* as a standalone repo would be simpler.
Diverse independent demo apps could then directly be forked as getting started templates..

**Comment by ataulm** [comment]
Closed: Volker is working on getting this fixed up - @devisnik could you update the readme with the outcome please?

**Pull request closed without merging**
